// <auto-generated />
using System;
using Diary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241109144130_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diary.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Today I went hiking w/ my friends.",
                            Created = new DateTime(2024, 11, 9, 15, 41, 29, 936, DateTimeKind.Local).AddTicks(7407),
                            Title = "Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Today I went swimming w/ my friends.",
                            Created = new DateTime(2024, 11, 9, 15, 41, 29, 936, DateTimeKind.Local).AddTicks(7409),
                            Title = "Swimming"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Today I went shopping w/ my friends.",
                            Created = new DateTime(2024, 11, 9, 15, 41, 29, 936, DateTimeKind.Local).AddTicks(7411),
                            Title = "Sshopping"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
